sv work \
--include "$REPO_ROOT/src" \
--include "$REPO_ROOT/verif/direct_tb" \
"$REPO_ROOT/verif/direct_tb/ama_riscv_tb.sv" \
"$REPO_ROOT/verif/direct_tb/ama_riscv_core_view.sv" \
"$REPO_ROOT/src/ama_riscv_top.sv" \
"$REPO_ROOT/src/ama_riscv_core_top.sv" \
"$REPO_ROOT/src/ama_riscv_core.sv" \
"$REPO_ROOT/src/ama_riscv_fe_ctrl.sv" \
"$REPO_ROOT/src/ama_riscv_decoder.sv" \
"$REPO_ROOT/src/ama_riscv_imm_gen.sv" \
"$REPO_ROOT/src/ama_riscv_bp.sv" \
"$REPO_ROOT/src/ama_riscv_pht.sv" \
"$REPO_ROOT/src/ama_riscv_operand_forwarding.sv" \
"$REPO_ROOT/src/ama_riscv_reg_file.sv" \
"$REPO_ROOT/src/ama_riscv_alu.sv" \
"$REPO_ROOT/src/cmp_s_lt.sv" \
"$REPO_ROOT/src/add.sv" \
"$REPO_ROOT/src/ama_riscv_mult.sv" \
"$REPO_ROOT/src/ama_riscv_simd.sv" \
"$REPO_ROOT/src/ama_riscv_simd_ppgen.sv" \
"$REPO_ROOT/src/ama_riscv_simd_data_fmt.sv" \
"$REPO_ROOT/src/csa.sv" \
"$REPO_ROOT/src/csa_tree_4.sv" \
"$REPO_ROOT/src/csa_tree_8.sv" \
"$REPO_ROOT/src/sat_s_add_sub.sv" \
"$REPO_ROOT/src/sat_u_add_sub.sv" \
"$REPO_ROOT/src/ama_riscv_simd_sat_clamp.sv" \
"$REPO_ROOT/src/sat_clamp.sv" \
"$REPO_ROOT/src/ama_riscv_simd_shift.sv" \
"$REPO_ROOT/src/barrel_shift_seg.sv" \
"$REPO_ROOT/src/bit_reverse.sv" \
"$REPO_ROOT/src/ama_riscv_simd_lane_wrapup.sv" \
"$REPO_ROOT/src/ama_riscv_div.sv" \
"$REPO_ROOT/src/lzc.sv" \
"$REPO_ROOT/src/ama_riscv_icache.sv" \
"$REPO_ROOT/src/ama_riscv_dcache.sv" \
"$REPO_ROOT/src/ama_riscv_mem.sv" \
"$REPO_ROOT/src/mem.sv" \
"$REPO_ROOT/src/ama_riscv_csr.sv" \
"$REPO_ROOT/src/ama_riscv_uart.sv" \
"$REPO_ROOT/src/uart.sv" \
"$REPO_ROOT/src/uart_tx.sv" \
"$REPO_ROOT/src/uart_rx.sv" \
